<a href="https://colab.research.google.com/github/Celinachc/Alura_Data_Science/blob/main/Aula06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importando numpy

In [1]:
import numpy as np

In [3]:
from numpy.random import default_rng

In [4]:
rng = default_rng()

In [21]:
# ids = rng.integers(low=15, high=1000, size=100)
size = 200
ids_sequenciais = np.arange(start=1, stop=1001, dtype=int)
ids = rng.choice(ids_sequenciais, size=size, replace=False)
idades = rng.integers(low=18, high=120, size=size)
sexo = rng.choice(['M','F'], size=size)
estados_civis = rng.choice(['solteiro', 'casado', 'divorciado', 'viuvo'], size=size)
sinistros = rng.integers(low=0, high=5, size=size)
premios = rng.normal(loc=1000, scale=200, size=size)


In [22]:
ids

array([834, 635, 426, 829, 968, 362, 446, 774, 302, 509, 454, 820, 195,
       404,  97, 937, 533, 782, 697, 908, 427, 995, 300, 263, 201, 570,
       227, 575, 335, 964, 713, 512,  73, 483, 631,   3, 329, 163, 467,
       495, 492, 965, 839, 588, 417, 795, 720, 769, 909, 790, 717, 240,
       364, 886, 346, 943, 112, 748, 593, 807,  22, 466, 579, 451, 412,
       602, 358, 322, 235, 479,  29, 285, 234,  40,  76, 516, 219, 958,
       992,   4, 591,  28, 975, 386, 520, 560, 143, 552, 442,  39, 108,
       961, 423, 587, 703, 334, 797, 292, 472, 424, 548, 563,  67, 392,
       526, 313, 811, 869, 974, 860, 410, 374, 237,  11, 601, 514, 382,
       574, 663, 106, 809, 576,  20, 361,  32, 331, 760, 862, 901,  44,
       282, 798, 153, 231, 507,  12, 729, 905, 128, 981,  96, 455, 930,
        68, 177, 336, 166, 732, 158, 389, 413, 944, 216, 612, 388, 494,
       799, 146, 982, 428, 911, 444, 327, 411, 138, 556, 202, 224, 741,
       198, 269, 646, 107, 754, 596,  70, 805, 132, 171, 753, 48

In [10]:
idades

array([ 22,  36,  45,  31,  70, 111,  90,  74,  82,  63,  57, 100,  65,
        67,  32, 100, 118, 107,  55,  24,  22,  96,  80, 101, 108,  32,
        66,  58,  55,  39,  99,  66, 101,  80,  97,  70,  24, 111,  55,
        99, 112,  88,  37,  99,  29,  43,  78,  81,  56, 117,  89,  91,
        74,  97,  49,  65,  38,  27,  33, 119, 117,  45, 109,  29,  89,
       119,  18,  86,  44,  20,  65, 103,  33,  35,  63,  42,  63,  92,
        70, 111,  23,  82,  52,  76,  76, 106,  94,  82, 106,  83,  67,
        22, 112,  56,  86,  79, 113, 103, 113,  58])

In [12]:
sexo

array(['M', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'F', 'M',
       'M', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'M',
       'M', 'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'F',
       'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M',
       'F', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'M',
       'F', 'F', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M',
       'M', 'F', 'F', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'M',
       'M', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'F'], dtype='<U1')

In [16]:
estados_civis

array(['solteiro', 'solteiro', 'solteiro', 'solteiro', 'casado',
       'solteiro', 'divorciado', 'casado', 'divorciado', 'casado',
       'divorciado', 'viuvo', 'solteiro', 'casado', 'solteiro',
       'solteiro', 'divorciado', 'divorciado', 'casado', 'viuvo',
       'solteiro', 'solteiro', 'casado', 'casado', 'casado', 'divorciado',
       'viuvo', 'casado', 'viuvo', 'divorciado', 'viuvo', 'casado',
       'viuvo', 'viuvo', 'casado', 'solteiro', 'viuvo', 'viuvo', 'casado',
       'divorciado', 'viuvo', 'viuvo', 'casado', 'divorciado', 'solteiro',
       'solteiro', 'solteiro', 'divorciado', 'solteiro', 'solteiro',
       'viuvo', 'viuvo', 'divorciado', 'divorciado', 'viuvo', 'solteiro',
       'viuvo', 'divorciado', 'solteiro', 'divorciado', 'viuvo', 'viuvo',
       'divorciado', 'solteiro', 'viuvo', 'viuvo', 'solteiro', 'solteiro',
       'viuvo', 'casado', 'casado', 'solteiro', 'divorciado', 'viuvo',
       'solteiro', 'divorciado', 'viuvo', 'casado', 'solteiro',
       'solteiro',

In [18]:
sinistros

array([3, 1, 2, 3, 4, 1, 2, 0, 4, 3, 3, 0, 1, 4, 0, 0, 3, 1, 0, 4, 2, 4,
       0, 4, 2, 1, 2, 0, 0, 1, 2, 0, 4, 0, 3, 4, 3, 4, 1, 0, 2, 1, 1, 4,
       0, 4, 0, 3, 2, 0, 1, 4, 3, 3, 4, 1, 4, 0, 4, 3, 0, 1, 0, 2, 4, 0,
       3, 4, 4, 1, 1, 0, 2, 4, 2, 1, 2, 1, 3, 4, 1, 0, 1, 0, 0, 0, 0, 3,
       4, 3, 4, 0, 0, 2, 2, 0, 2, 4, 1, 3])

In [20]:
premios

array([ 877.51752639,  816.32300883, 1246.36353928, 1189.15134932,
       1127.79506389, 1126.95549176, 1032.87849509,  873.65421067,
        693.87546645,  864.44003306, 1029.0183761 ,  841.20409484,
       1110.44342278,  873.21214529, 1382.69577493,  800.66724921,
        871.20820255,  796.17483041, 1206.23474876,  910.96431802,
        907.1697338 , 1188.89510287,  928.63601726, 1096.7407687 ,
       1425.93780745, 1135.86284773,  919.04349816, 1183.28720314,
        846.3424144 , 1112.13996252, 1197.87042011, 1048.87052843,
        727.89996055,  630.32954298, 1015.61392771, 1130.93428972,
        795.75659922, 1232.57986645, 1005.27556902,  908.4416237 ,
       1267.92351249, 1076.51133451,  991.55709879,  883.2027301 ,
       1128.36769588,  942.89612458, 1034.66456751, 1090.68455539,
       1118.98951046, 1002.99267886, 1025.65100414,  821.47490613,
        846.65968644, 1087.31714244,  554.40428099,  741.07831162,
       1009.24036768,  799.64791253, 1284.38170818,  913.44114

In [23]:
np.sum(idades > 30)

175

In [24]:
idades_maior_30 = idades > 30

In [25]:
idades_maior_30

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [27]:
idades[idades_maior_30]

array([ 77, 111,  63, 102,  35,  95,  51,  72,  75,  34,  62,  89,  90,
        92,  75, 114,  75,  59,  94,  44,  88,  38,  63,  71,  34,  42,
        96,  68, 111,  60, 104,  86, 103,  78,  43,  96,  55,  72,  58,
        69,  94,  78,  80, 107, 100,  68,  60,  72,  60, 113,  51,  44,
        44,  36,  42,  74, 117,  67,  32,  74, 116,  81,  60,  48,  36,
       106,  46,  92,  78,  85,  69,  90,  39, 108,  52,  38,  64,  38,
        92, 110, 112,  61,  94,  32,  42,  99, 118, 119,  46,  87,  31,
       102,  47,  42,  31,  96, 102,  55,  36, 118,  58,  45,  86,  91,
        82, 119,  71,  31,  58,  32,  43,  87,  75,  94,  96,  98, 101,
        47,  36,  75,  45,  33,  67,  54, 113,  79,  32,  69,  51,  82,
        69,  99, 111, 105, 108,  47,  34,  54,  37,  69, 114,  53,  56,
        78,  53,  83,  93,  74,  47,  35, 112,  91,  83,  48,  67, 112,
        53, 117, 108,  70,  47, 107,  69, 108,  99,  77,  42, 119,  83,
       108,  54,  35, 101,  95, 100])